spring:
  application:
    name: simple-server
server:
  port: 8089

monitor:
  name: app
  centerUrl: http://127.0.0.1:18500/v1/agent/service/register
#  ip: 127.0.0.1
  port: 8091
  tag:
    - service:simpleapp
    - cluster:prod
    - dc:bj
    - nodename:app1